name: Build and deploy ASP.Net Core app to Azure Web App - fleetflow-app-24103433

on:
  push:
    branches:
      - develop
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - uses: actions/checkout@v4

      - name: Set up .NET Core
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '10.x'

      - name: Build with dotnet
        run: dotnet build src/backend/services/IdentityService/IdentityService.Api/IdentityService.Api.csproj --configuration Release

      - name: dotnet publish
        run: dotnet publish src/backend/services/IdentityService/IdentityService.Api/IdentityService.Api.csproj -c Release -o ${{env.DOTNET_ROOT}}/myapp

      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v4
        with:
          name: .net-app
          path: ${{env.DOTNET_ROOT}}/myapp

  deploy:
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: .net-app
          path: myapp

      - name: Deploy to Azure Web App
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'fleetflow-app-24103433'
          slot-name: 'Production'
          package: myapp
          publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE_2CE1B6B5B5A84EEDA31D3A67747DFB4B }}
